const profile1 = "/icons/7e72a7998be770ff0cd3794fba26c10791f7cb58.png";
const profile2 = "/icons/70956c3e4bf1aab578cf67e015bc27eb5d8014a7.png";
const profile3 = "/icons/27329e3b78d83b20619fddee55560c05c2cd1469.png";
const profile4 = "/icons/426cc48c65f01a64ae4fb95e309fac55efcf3530.png";
const profile5 = "/icons/426cc48c65f01a64ae4fb95e309fac55efcf3530.png";

export const Projects = [
  {
    title: 'Project 1',
    description: 'Successfully integrated Stripe payment gateway with error handling and webhook support',
    ProjectId: 'PJ-01',
    startDate: '01 Sep 2025',
    endDate: '02 Sep 2025',
    process: 90,
    client: {
      name: 'TechCorp Industries',
    },
    projectManager: {
      name: 'Anitha',
      profile: profile2,
    },
    assignee: [
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
    ],
  },
  {
    title: 'Project 2',
    description: 'Developing a real-time chat application with WebSocket and push notifications',
    ProjectId: 'PJ-02',
    startDate: '03 Sep 2025',
    endDate: '20 Sep 2025',
    process: 65,
    client: { name: 'InnovaSoft' },
    projectManager: { name: 'Ravi', profile: profile4 },
    assignee: [
      { name: 'Meena', profile: profile2 },
      { name: 'Karthik', profile: profile5 },
    ],
  },
  {
    title: 'Project 3',
    description: 'Redesign of e-commerce platform with Next.js and Tailwind',
    ProjectId: 'PJ-03',
    startDate: '05 Sep 2025',
    endDate: '30 Sep 2025',
    process: 40,
    client: { name: 'ShopEase Pvt Ltd' },
    projectManager: { name: 'Kavya', profile: profile1 },
    assignee: [
      { name: 'Suresh', profile: profile3 },
      { name: 'Dinesh', profile: profile4 },
    ],
  },
  {
    title: 'Project 4',
    description: 'AI-powered HR analytics dashboard with predictive insights',
    ProjectId: 'PJ-04',
    startDate: '08 Sep 2025',
    endDate: '15 Oct 2025',
    process: 25,
    client: { name: 'PeopleFirst HR' },
    projectManager: { name: 'Mohan', profile: profile3 },
    assignee: [
      { name: 'Anitha', profile: profile2 },
      { name: 'Karthik', profile: profile5 },
    ],
  },
  {
    title: 'Project 5',
    description: 'Healthcare appointment scheduling system with calendar sync',
    ProjectId: 'PJ-05',
    startDate: '10 Sep 2025',
    endDate: '10 Oct 2025',
    process: 55,
    client: { name: 'MediConnect' },
    projectManager: { name: 'Divya', profile: profile5 },
    assignee: [
      { name: 'Meena', profile: profile2 },
      { name: 'Kamalesh', profile: profile1 },
    ],
  },
  {
    title: 'Project 6',
    description: 'IoT-based fleet tracking system with live map integration',
    ProjectId: 'PJ-06',
    startDate: '12 Sep 2025',
    endDate: '05 Nov 2025',
    process: 15,
    client: { name: 'TransLogix' },
    projectManager: { name: 'Ravi', profile: profile4 },
    assignee: [
      { name: 'Dinesh', profile: profile4 },
      { name: 'Suresh', profile: profile3 },
    ],
  },
  {
    title: 'Project 7',
    description: 'Learning Management System with role-based dashboards',
    ProjectId: 'PJ-07',
    startDate: '15 Sep 2025',
    endDate: '15 Nov 2025',
    process: 35,
    client: { name: 'EduCore Systems' },
    projectManager: { name: 'Anitha', profile: profile2 },
    assignee: [
      { name: 'Karthik', profile: profile5 },
      { name: 'Divya', profile: profile5 },
    ],
  },
  {
    title: 'Project 8',
    description: 'Banking mobile app with biometric authentication',
    ProjectId: 'PJ-08',
    startDate: '18 Sep 2025',
    endDate: '20 Dec 2025',
    process: 10,
    client: { name: 'FinTrust Bank' },
    projectManager: { name: 'Kavya', profile: profile1 },
    assignee: [
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Meena', profile: profile2 },
    ],
  },
  {
    title: 'Project 9',
    description: 'Cloud migration for legacy enterprise applications',
    ProjectId: 'PJ-09',
    startDate: '20 Sep 2025',
    endDate: '30 Nov 2025',
    process: 60,
    client: { name: 'NextGen Solutions' },
    projectManager: { name: 'Mohan', profile: profile3 },
    assignee: [
      { name: 'Suresh', profile: profile3 },
      { name: 'Divya', profile: profile5 },
    ],
  },
  {
    title: 'Project 10',
    description: 'Blockchain-based supply chain management platform',
    ProjectId: 'PJ-10',
    startDate: '25 Sep 2025',
    endDate: '25 Dec 2025',
    process: 5,
    client: { name: 'ChainX Logistics' },
    projectManager: { name: 'Ravi', profile: profile4 },
    assignee: [
      { name: 'Karthik', profile: profile5 },
      { name: 'Meena', profile: profile2 },
    ],
  },
  {
    title: 'Project 11',
    description: 'Smart city dashboard with IoT data visualization',
    ProjectId: 'PJ-11',
    startDate: '28 Sep 2025',
    endDate: '15 Jan 2026',
    process: 50,
    client: { name: 'UrbanTech' },
    projectManager: { name: 'Divya', profile: profile5 },
    assignee: [
      { name: 'Kamalesh', profile: profile1 },
      { name: 'Suresh', profile: profile3 },
    ],
  },
];

export const Chats = [
    {
      name: 'Kamalesh',
      lastmsg: 'Sure, let’s do 6 PM!',
      profile: profile1,
      ispin: true,
      unread: 4,
      activeago: '5 min ago',
      conversations: [
        { sender: "Suresh", text: "Hey, how are you?", timestamp: "2025-08-25T09:30:00Z" },
        { sender: "Kamalesh", text: "I’m good! What about you?", timestamp: "2025-08-25T09:31:00Z" },
        { sender: "Suresh", text: "Same here. Want to catch up later?", timestamp: "2025-08-25T09:32:00Z" },
        { sender: "Kamalesh", text: "Sure, let’s do 6 PM!", timestamp: "2025-08-25T09:33:00Z" },
      ],
    },
    {
      name: 'Priya',
      lastmsg: 'Got it, will fix and push update.',
      profile: profile2,
      ispin: false,
      unread: 2,
      activeago: '10 min ago',
      conversations: [
        { sender: "Priya", text: "Hey, did you check the latest design?", timestamp: "2025-08-25T10:00:00Z" },
        { sender: "Kamalesh", text: "Yes, looks great! Maybe adjust the sidebar spacing?", timestamp: "2025-08-25T10:01:00Z" },
        { sender: "Priya", text: "Got it, will fix and push update.", timestamp: "2025-08-25T10:02:00Z" },
      ],
    },
    {
      name: 'Arun',
      lastmsg: 'Cool 👍',
      profile: profile3,
      ispin: false,
      unread: 0,
      activeago: '20 min ago',
      conversations: [
        { sender: "Arun", text: "Morning! Are you joining the meeting?", timestamp: "2025-08-25T08:45:00Z" },
        { sender: "Kamalesh", text: "Yes, I’ll be there in 5 mins.", timestamp: "2025-08-25T08:46:00Z" },
        { sender: "Arun", text: "Cool 👍", timestamp: "2025-08-25T08:47:00Z" },
      ],
    },
    {
      name: 'Divya',
      lastmsg: 'Haha 😂 I know!',
      profile: profile4,
      ispin: true,
      unread: 5,
      activeago: '30 min ago',
      conversations: [
        { sender: "Divya", text: "Did you watch the new movie?", timestamp: "2025-08-24T21:15:00Z" },
        { sender: "Kamalesh", text: "Not yet, was it good?", timestamp: "2025-08-24T21:16:00Z" },
        { sender: "Divya", text: "It was awesome, you’ll love it!", timestamp: "2025-08-24T21:18:00Z" },
        { sender: "Kamalesh", text: "Haha 😂 I know!", timestamp: "2025-08-24T21:19:00Z" },
      ],
    },
    {
      name: 'Suresh',
      lastmsg: 'Let’s finalize it tomorrow.',
      profile: profile5,
      ispin: false,
      unread: 1,
      activeago: '1 hr ago',
      conversations: [
        { sender: "Suresh", text: "Did you finish the report?", timestamp: "2025-08-24T18:30:00Z" },
        { sender: "Kamalesh", text: "Almost done, need a few more edits.", timestamp: "2025-08-24T18:32:00Z" },
        { sender: "Suresh", text: "Okay cool. Let’s finalize it tomorrow.", timestamp: "2025-08-24T18:33:00Z" },
      ],
    },
    {
      name: 'Ananya',
      lastmsg: 'Alright, talk to you later!',
      profile: profile2,
      ispin: false,
      unread: 3,
      activeago: '2 hr ago',
      conversations: [
        { sender: "Ananya", text: "Hey, free to chat?", timestamp: "2025-08-24T16:10:00Z" },
        { sender: "Kamalesh", text: "Yes, tell me.", timestamp: "2025-08-24T16:11:00Z" },
        { sender: "Ananya", text: "Just wanted some advice on the presentation.", timestamp: "2025-08-24T16:12:00Z" },
        { sender: "Kamalesh", text: "Sure, share it with me.", timestamp: "2025-08-24T16:13:00Z" },
        { sender: "Ananya", text: "Alright, talk to you later!", timestamp: "2025-08-24T16:15:00Z" },
      ],
    },
    {
      name: 'Rahul',
      lastmsg: 'Thanks bro!',
      profile: profile3,
      ispin: true,
      unread: 0,
      activeago: '3 hr ago',
      conversations: [
        { sender: "Rahul", text: "Can you send me that document?", timestamp: "2025-08-24T14:20:00Z" },
        { sender: "Kamalesh", text: "Sure, give me a sec.", timestamp: "2025-08-24T14:21:00Z" },
        { sender: "Rahul", text: "Got it. Thanks bro!", timestamp: "2025-08-24T14:22:00Z" },
      ],
    },
    {
      name: 'Meera',
      lastmsg: 'Yes, I’ll be ready.',
      profile: profile1,
      ispin: false,
      unread: 6,
      activeago: '4 hr ago',
      conversations: [
        { sender: "Meera", text: "Are you coming to the party?", timestamp: "2025-08-24T12:45:00Z" },
        { sender: "Kamalesh", text: "Yes! Need to pick up a gift first.", timestamp: "2025-08-24T12:46:00Z" },
        { sender: "Meera", text: "Cool, see you there.", timestamp: "2025-08-24T12:47:00Z" },
        { sender: "Kamalesh", text: "Will you be on time?", timestamp: "2025-08-24T12:48:00Z" },
        { sender: "Meera", text: "Yes, I’ll be ready.", timestamp: "2025-08-24T12:49:00Z" },
      ],
    },
    {
      name: 'Vikram',
      lastmsg: 'Catch you tomorrow!',
      profile: profile4,
      ispin: false,
      unread: 0,
      activeago: 'Yesterday',
      conversations: [
        { sender: "Vikram", text: "Game night today?", timestamp: "2025-08-23T20:00:00Z" },
        { sender: "Kamalesh", text: "Yes, but I might be late.", timestamp: "2025-08-23T20:01:00Z" },
        { sender: "Vikram", text: "No worries. Catch you tomorrow!", timestamp: "2025-08-23T20:02:00Z" },
      ],
    },
    {
      name: 'Neha',
      lastmsg: 'Good night 🌙',
      profile: profile2,
      ispin: true,
      unread: 7,
      activeago: '2 days ago',
      conversations: [
        { sender: "Neha", text: "Hey, are you free?", timestamp: "2025-08-22T22:10:00Z" },
        { sender: "Kamalesh", text: "Yes, what’s up?", timestamp: "2025-08-22T22:11:00Z" },
        { sender: "Neha", text: "Just wanted to say thanks for your help today.", timestamp: "2025-08-22T22:12:00Z" },
        { sender: "Kamalesh", text: "Anytime 😊", timestamp: "2025-08-22T22:13:00Z" },
        { sender: "Neha", text: "Good night 🌙", timestamp: "2025-08-22T22:15:00Z" },
      ],
    },
  ];
  
  